#!/bin/bash

export HOME=/home/hara
export CURRENT=/home/hara/production/current/script

export rvm_scripts_path=/home/hara/.rvm/scripts
export rvm_bin_path=/home/hara/.rvm/bin
export GEM_HOME=/home/hara/.rvm/gems/ruby-1.9.1-p378
export TERM=xterm-color
export SHELL=/bin/bash
export IRBRC=/home/hara/.rvm/rubies/ruby-1.9.1-p378/.irbrc
export MY_RUBY_HOME=/home/hara/.rvm/rubies/ruby-1.9.1-p378
export SSH_TTY=/dev/pts/6
export USER=hara
export rvm_gems_cache_path=/home/hara/.rvm/gems/cache
export rvm_config_path=/home/hara/.rvm/config
export rvm_path=/home/hara/.rvm
export rvm_gemset_separator=@
export MAIL=/var/mail/hara
export PATH=/home/hara/.rvm/rubies/ruby-1.9.1-p378/bin:/home/hara/.rvm/gems/ruby-1.9.1-p378/bin:/home/hara/.rvm/gems/ruby-1.9.1-p378@global/bin:/home/hara/.rvm/bin:/home/hara/.rvm/rubies/ruby-1.9.1-p378/bin:/home/hara/.rvm/gems/ruby-1.9.1-p378/bin:/home/hara/.rvm/gems/ruby-1.9.1-p378@global/bin:/home/hara/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
export rvm_rubies_path=/home/hara/.rvm/rubies
export PWD=/home/hara/production/current
export LANG=ru_RU.UTF-8
export rvm_hooks_path=/home/hara/.rvm/hooks
export rvm_version=0.1.28
export rvm_src_path=/home/hara/.rvm/src
export SHLVL=1
export HOME=/home/hara
export rvm_gems_path=/home/hara/.rvm/gems
export RAILS_ENV=production
export rvm_ruby_string=ruby-1.9.1-p378
export BUNDLE_PATH=/home/hara/.rvm/gems/ruby-1.9.1-p378
export rvm_tmp_path=/home/hara/.rvm/tmp
export LOGNAME=hara
export GEM_PATH=/home/hara/.rvm/gems/ruby-1.9.1-p378:/home/hara/.rvm/gems/ruby-1.9.1-p378@global
export rvm_log_path=/home/hara/.rvm/log
export RUBYOPT=-Ku
export rvm_archives_path=/home/hara/.rvm/archives
export _=/usr/bin/env
export OLDPWD=/home/hara/productio


if [ $# != 2 ]; then
  echo "Usage: startd RAILS_ENV 'daemon start|stop'"
  exit
fi

# starting script
#sleep 15 # ждем, потому что скрирт уже может быть запущен, но пид еще не создался
RAILS_ENV=$1 $CURRENT/$2

